import type { GalleryArtwork } from "./types";

// ── Selection gallery — one preview piece per artist ─────────────────────────
export const galleryArtworks: GalleryArtwork[] = [
  {
    id: "silent-door",
    title: "The Silent Door",
    subtitle: "A threshold between memory and distance",
    imageSrc: "/art/art-1.jpg",
    poem: "Between stone and breath,\nthe silence learned my name.",
    medium: "Oil on linen",
    dimensions: "120 × 160 cm",
    year: 2022,
    likes: "3.4k",
    comments: "218",
    artist: { name: "Noor Al-Rashid", style: "Contemplative Abstraction", followers: "18.4k", supporters: "312", visitors: "2.1M" },
  },
  {
    id: "ashen-field",
    title: "Ashen Field",
    subtitle: "What remains after the fire forgets itself",
    imageSrc: "/art/art-1.jpg",
    poem: "The grass does not mourn.\nIt only waits, and waits.",
    medium: "Mixed media on canvas",
    dimensions: "90 × 130 cm",
    year: 2021,
    likes: "1.1k",
    comments: "74",
    artist: { name: "Leila Voss", style: "Textural Realism", followers: "9.7k", supporters: "145", visitors: "874k" },
  },
  {
    id: "mirror-weight",
    title: "Mirror Weight",
    subtitle: "Reflections carry more than light",
    imageSrc: "/art/art-1.jpg",
    poem: "You looked back\nand found yourself already gone.",
    medium: "Acrylic and resin on panel",
    dimensions: "100 × 100 cm",
    year: 2023,
    likes: "9.8k",
    comments: "541",
    artist: { name: "Tariq Henson", style: "Psychological Surrealism", followers: "31.2k", supporters: "580", visitors: "5.4M" },
  },
  {
    id: "blue-departure",
    title: "Blue Departure",
    subtitle: "A farewell painted in the hour before dawn",
    imageSrc: "/art/art-1.jpg",
    poem: "Not every leaving\nhas a name for itself.",
    medium: "Watercolour on paper",
    dimensions: "70 × 100 cm",
    year: 2020,
    likes: "6.2k",
    comments: "329",
    artist: { name: "Amara Osei", style: "Lyrical Minimalism", followers: "22.1k", supporters: "410", visitors: "3.8M" },
  },
  {
    id: "the-weight-of-rooms",
    title: "The Weight of Rooms",
    subtitle: "Spaces that remember who lived in them",
    imageSrc: "/art/art-1.jpg",
    poem: "Empty chairs\nare the loudest kind of presence.",
    medium: "Oil on canvas",
    dimensions: "150 × 200 cm",
    year: 2024,
    likes: "2.7k",
    comments: "183",
    artist: { name: "Selin Çelik", style: "Intimate Expressionism", followers: "14.8k", supporters: "229", visitors: "1.6M" },
  },
  {
    id: "orbit-of-grief",
    title: "Orbit of Grief",
    subtitle: "Some emotions circle you for years",
    imageSrc: "/art/art-1.jpg",
    poem: "It does not land.\nIt only keeps returning.",
    medium: "Ink and graphite on paper",
    dimensions: "80 × 80 cm",
    year: 2019,
    likes: "892",
    comments: "61",
    artist: { name: "Marcus Frei", style: "Dark Geometric", followers: "6.3k", supporters: "88", visitors: "490k" },
  },
  {
    id: "pale-archive",
    title: "Pale Archive",
    subtitle: "Documents of a life no one filed",
    imageSrc: "/art/art-1.jpg",
    poem: "The records say nothing\nabout what was loved.",
    medium: "Archival pigment print",
    dimensions: "110 × 140 cm",
    year: 2022,
    likes: "14.1k",
    comments: "702",
    artist: { name: "Yuki Tanabe", style: "Archival Conceptualism", followers: "41.0k", supporters: "764", visitors: "7.2M" },
  },
  {
    id: "threshold-song",
    title: "Threshold Song",
    subtitle: "The melody that plays between worlds",
    imageSrc: "/art/art-1.jpg",
    poem: "Somewhere between here\nand forgetting, music lives.",
    medium: "Digital print on aluminium",
    dimensions: "95 × 120 cm",
    year: 2023,
    likes: "2.3k",
    comments: "156",
    artist: { name: "Daria Molnár", style: "Sonic Abstraction", followers: "12.5k", supporters: "197", visitors: "1.1M" },
  },
  {
    id: "still-water-hour",
    title: "Still Water Hour",
    subtitle: "When the surface holds more than the depth",
    imageSrc: "/art/art-1.jpg",
    poem: "Stillness is not silence.\nIt is waiting that has learned patience.",
    medium: "Oil and cold wax on board",
    dimensions: "130 × 130 cm",
    year: 2021,
    likes: "7.5k",
    comments: "414",
    artist: { name: "Ravi Menon", style: "Meditative Naturalism", followers: "27.6k", supporters: "503", visitors: "4.3M" },
  },
];

// ── Per-artist collections ─────────────────────────────────────────────────
export const artistCollections: Record<string, GalleryArtwork[]> = {
  "silent-door": [
    { id: "nr-1", title: "Hollow Afternoon", subtitle: "The hour that swallowed itself whole", imageSrc: "/art/art-1.jpg", poem: "Light did not leave.\nIt simply stopped arriving.", medium: "Oil on linen", dimensions: "100 × 140 cm", year: 2021, artist: { name: "Noor Al-Rashid", style: "Contemplative Abstraction", followers: "18.4k", supporters: "312", visitors: "2.1M" } },
    { id: "nr-2", title: "Between Two Walls", subtitle: "A space neither inside nor outside", imageSrc: "/art/art-1.jpg", poem: "Some distances\nare not made of steps.", medium: "Charcoal on paper", dimensions: "60 × 90 cm", year: 2020, artist: { name: "Noor Al-Rashid", style: "Contemplative Abstraction", followers: "18.4k", supporters: "312", visitors: "2.1M" } },
    { id: "nr-3", title: "The Silent Door", subtitle: "A threshold between memory and distance", imageSrc: "/art/art-1.jpg", poem: "Between stone and breath,\nthe silence learned my name.", medium: "Oil on linen", dimensions: "120 × 160 cm", year: 2022, artist: { name: "Noor Al-Rashid", style: "Contemplative Abstraction", followers: "18.4k", supporters: "312", visitors: "2.1M" } },
    { id: "nr-4", title: "Unnamed Room", subtitle: "A place that never needed a name", imageSrc: "/art/art-1.jpg", poem: "I left no mark.\nThe room remembers anyway.", medium: "Encaustic on panel", dimensions: "80 × 100 cm", year: 2023, artist: { name: "Noor Al-Rashid", style: "Contemplative Abstraction", followers: "18.4k", supporters: "312", visitors: "2.1M" } },
  ],
  "ashen-field": [
    { id: "lv-1", title: "Ashen Field", subtitle: "What remains after the fire forgets itself", imageSrc: "/art/art-1.jpg", poem: "The grass does not mourn.\nIt only waits, and waits.", medium: "Mixed media on canvas", dimensions: "90 × 130 cm", year: 2021, artist: { name: "Leila Voss", style: "Textural Realism", followers: "9.7k", supporters: "145", visitors: "874k" } },
    { id: "lv-2", title: "Worn Surface", subtitle: "Every scratch is a year", imageSrc: "/art/art-1.jpg", poem: "The wall did not crack.\nIt simply told the truth.", medium: "Oil and sand on canvas", dimensions: "75 × 100 cm", year: 2019, artist: { name: "Leila Voss", style: "Textural Realism", followers: "9.7k", supporters: "145", visitors: "874k" } },
    { id: "lv-3", title: "Salt and Stone", subtitle: "Textures pulled from the shoreline", imageSrc: "/art/art-1.jpg", poem: "The sea does not explain.\nIt arrives, and that is enough.", medium: "Acrylic and salt on board", dimensions: "60 × 80 cm", year: 2022, artist: { name: "Leila Voss", style: "Textural Realism", followers: "9.7k", supporters: "145", visitors: "874k" } },
  ],
  "mirror-weight": [
    { id: "th-1", title: "Mirror Weight", subtitle: "Reflections carry more than light", imageSrc: "/art/art-1.jpg", poem: "You looked back\nand found yourself already gone.", medium: "Acrylic and resin on panel", dimensions: "100 × 100 cm", year: 2023, artist: { name: "Tariq Henson", style: "Psychological Surrealism", followers: "31.2k", supporters: "580", visitors: "5.4M" } },
    { id: "th-2", title: "The Other Side of Sleep", subtitle: "Dreams that remember you", imageSrc: "/art/art-1.jpg", poem: "In the dream you were there.\nIn the morning you were twice gone.", medium: "Oil on canvas", dimensions: "120 × 150 cm", year: 2022, artist: { name: "Tariq Henson", style: "Psychological Surrealism", followers: "31.2k", supporters: "580", visitors: "5.4M" } },
    { id: "th-3", title: "Doubling", subtitle: "When the self becomes plural", imageSrc: "/art/art-1.jpg", poem: "I met myself halfway.\nNeither of us spoke.", medium: "Digital print on glass", dimensions: "90 × 90 cm", year: 2021, artist: { name: "Tariq Henson", style: "Psychological Surrealism", followers: "31.2k", supporters: "580", visitors: "5.4M" } },
    { id: "th-4", title: "Portrait of an Echo", subtitle: "What sound looks like after it fades", imageSrc: "/art/art-1.jpg", poem: "I said your name once.\nThe room held it longer than I did.", medium: "Charcoal and resin on panel", dimensions: "80 × 110 cm", year: 2024, artist: { name: "Tariq Henson", style: "Psychological Surrealism", followers: "31.2k", supporters: "580", visitors: "5.4M" } },
  ],
  "blue-departure": [
    { id: "ao-1", title: "Blue Departure", subtitle: "A farewell painted in the hour before dawn", imageSrc: "/art/art-1.jpg", poem: "Not every leaving\nhas a name for itself.", medium: "Watercolour on paper", dimensions: "70 × 100 cm", year: 2020, artist: { name: "Amara Osei", style: "Lyrical Minimalism", followers: "22.1k", supporters: "410", visitors: "3.8M" } },
    { id: "ao-2", title: "One Line", subtitle: "Everything reduced to its essential gesture", imageSrc: "/art/art-1.jpg", poem: "A single mark\ncontained the whole story.", medium: "Ink on paper", dimensions: "50 × 70 cm", year: 2019, artist: { name: "Amara Osei", style: "Lyrical Minimalism", followers: "22.1k", supporters: "410", visitors: "3.8M" } },
    { id: "ao-3", title: "Pale Intention", subtitle: "What you meant before words", imageSrc: "/art/art-1.jpg", poem: "Before I spoke\nthere was a color. It was this.", medium: "Gouache on panel", dimensions: "60 × 80 cm", year: 2022, artist: { name: "Amara Osei", style: "Lyrical Minimalism", followers: "22.1k", supporters: "410", visitors: "3.8M" } },
  ],
  "the-weight-of-rooms": [
    { id: "sc-1", title: "The Weight of Rooms", subtitle: "Spaces that remember who lived in them", imageSrc: "/art/art-1.jpg", poem: "Empty chairs\nare the loudest kind of presence.", medium: "Oil on canvas", dimensions: "150 × 200 cm", year: 2024, artist: { name: "Selin Çelik", style: "Intimate Expressionism", followers: "14.8k", supporters: "229", visitors: "1.6M" } },
    { id: "sc-2", title: "Soft Violence", subtitle: "The tenderness that leaves marks", imageSrc: "/art/art-1.jpg", poem: "You were gentle\nin ways that still hurt.", medium: "Pastel on velvet", dimensions: "70 × 90 cm", year: 2023, artist: { name: "Selin Çelik", style: "Intimate Expressionism", followers: "14.8k", supporters: "229", visitors: "1.6M" } },
    { id: "sc-3", title: "After the Guest Left", subtitle: "A room mid-transition", imageSrc: "/art/art-1.jpg", poem: "The impression in the cushion\nwas all that remained.", medium: "Oil on linen", dimensions: "100 × 130 cm", year: 2022, artist: { name: "Selin Çelik", style: "Intimate Expressionism", followers: "14.8k", supporters: "229", visitors: "1.6M" } },
    { id: "sc-4", title: "Before the Morning", subtitle: "The slow weight of almost-dawn", imageSrc: "/art/art-1.jpg", poem: "The sky didn't brighten.\nIt just became less dark.", medium: "Acrylic on canvas", dimensions: "120 × 160 cm", year: 2021, artist: { name: "Selin Çelik", style: "Intimate Expressionism", followers: "14.8k", supporters: "229", visitors: "1.6M" } },
  ],
  "orbit-of-grief": [
    { id: "mf-1", title: "Orbit of Grief", subtitle: "Some emotions circle you for years", imageSrc: "/art/art-1.jpg", poem: "It does not land.\nIt only keeps returning.", medium: "Ink and graphite on paper", dimensions: "80 × 80 cm", year: 2019, artist: { name: "Marcus Frei", style: "Dark Geometric", followers: "6.3k", supporters: "88", visitors: "490k" } },
    { id: "mf-2", title: "Hard Angle", subtitle: "What geometry looks like under pressure", imageSrc: "/art/art-1.jpg", poem: "The corner held.\nEverything else gave way.", medium: "Laser-cut steel on board", dimensions: "60 × 60 cm", year: 2021, artist: { name: "Marcus Frei", style: "Dark Geometric", followers: "6.3k", supporters: "88", visitors: "490k" } },
    { id: "mf-3", title: "Collapse Study No. 4", subtitle: "Structures that fail beautifully", imageSrc: "/art/art-1.jpg", poem: "It fell with precision.\nAs if it had planned this.", medium: "Graphite on paper", dimensions: "70 × 100 cm", year: 2022, artist: { name: "Marcus Frei", style: "Dark Geometric", followers: "6.3k", supporters: "88", visitors: "490k" } },
  ],
  "pale-archive": [
    { id: "yt-1", title: "Pale Archive", subtitle: "Documents of a life no one filed", imageSrc: "/art/art-1.jpg", poem: "The records say nothing\nabout what was loved.", medium: "Archival pigment print", dimensions: "110 × 140 cm", year: 2022, artist: { name: "Yuki Tanabe", style: "Archival Conceptualism", followers: "41.0k", supporters: "764", visitors: "7.2M" } },
    { id: "yt-2", title: "Catalogue of Losses", subtitle: "Filed, numbered, unfound", imageSrc: "/art/art-1.jpg", poem: "Everything was documented.\nNothing was understood.", medium: "Letterpress on archival paper", dimensions: "60 × 90 cm", year: 2020, artist: { name: "Yuki Tanabe", style: "Archival Conceptualism", followers: "41.0k", supporters: "764", visitors: "7.2M" } },
    { id: "yt-3", title: "Reference Without Object", subtitle: "A system that outlived its contents", imageSrc: "/art/art-1.jpg", poem: "The index remained.\nThe things it pointed to did not.", medium: "Digital print on vellum", dimensions: "80 × 120 cm", year: 2023, artist: { name: "Yuki Tanabe", style: "Archival Conceptualism", followers: "41.0k", supporters: "764", visitors: "7.2M" } },
    { id: "yt-4", title: "Blank Entry", subtitle: "What was not recorded", imageSrc: "/art/art-1.jpg", poem: "The field was left empty.\nThat too is an answer.", medium: "Embossed paper", dimensions: "50 × 70 cm", year: 2024, artist: { name: "Yuki Tanabe", style: "Archival Conceptualism", followers: "41.0k", supporters: "764", visitors: "7.2M" } },
  ],
  "threshold-song": [
    { id: "dm-1", title: "Threshold Song", subtitle: "The melody that plays between worlds", imageSrc: "/art/art-1.jpg", poem: "Somewhere between here\nand forgetting, music lives.", medium: "Digital print on aluminium", dimensions: "95 × 120 cm", year: 2023, artist: { name: "Daria Molnár", style: "Sonic Abstraction", followers: "12.5k", supporters: "197", visitors: "1.1M" } },
    { id: "dm-2", title: "Frequency", subtitle: "What the body hears before the mind does", imageSrc: "/art/art-1.jpg", poem: "The low note arrived\nbefore the sound did.", medium: "Oscilloscope print on paper", dimensions: "70 × 100 cm", year: 2021, artist: { name: "Daria Molnár", style: "Sonic Abstraction", followers: "12.5k", supporters: "197", visitors: "1.1M" } },
    { id: "dm-3", title: "Resonance Study", subtitle: "A room listening to itself", imageSrc: "/art/art-1.jpg", poem: "The walls held the note\nlong after the singing stopped.", medium: "Acrylic on canvas", dimensions: "80 × 80 cm", year: 2022, artist: { name: "Daria Molnár", style: "Sonic Abstraction", followers: "12.5k", supporters: "197", visitors: "1.1M" } },
  ],
  "still-water-hour": [
    { id: "rm-1", title: "Still Water Hour", subtitle: "When the surface holds more than the depth", imageSrc: "/art/art-1.jpg", poem: "Stillness is not silence.\nIt is waiting that has learned patience.", medium: "Oil and cold wax on board", dimensions: "130 × 130 cm", year: 2021, artist: { name: "Ravi Menon", style: "Meditative Naturalism", followers: "27.6k", supporters: "503", visitors: "4.3M" } },
    { id: "rm-2", title: "Root System", subtitle: "What grows where no one is watching", imageSrc: "/art/art-1.jpg", poem: "Beneath the visible world\nsomething quiet was always working.", medium: "Watercolour on paper", dimensions: "90 × 120 cm", year: 2020, artist: { name: "Ravi Menon", style: "Meditative Naturalism", followers: "27.6k", supporters: "503", visitors: "4.3M" } },
    { id: "rm-3", title: "Season Without Name", subtitle: "Between autumn and nothing", imageSrc: "/art/art-1.jpg", poem: "The year paused here.\nNo one thought to mark it.", medium: "Oil on linen", dimensions: "100 × 140 cm", year: 2022, artist: { name: "Ravi Menon", style: "Meditative Naturalism", followers: "27.6k", supporters: "503", visitors: "4.3M" } },
    { id: "rm-4", title: "The Patient Earth", subtitle: "Geological time rendered intimate", imageSrc: "/art/art-1.jpg", poem: "The stone does not hurry.\nIt has decided to become.", medium: "Oil and pigment on canvas", dimensions: "120 × 160 cm", year: 2023, artist: { name: "Ravi Menon", style: "Meditative Naturalism", followers: "27.6k", supporters: "503", visitors: "4.3M" } },
  ],
};

